### ISSUE TITLE
`cronv` installation instruction clarification

### ISSUE THREAD

**Issue by HerbCSO** [takumakanari/cronv#10]
Pardon my ignorance, I'm not actually familiar with the Go ecosystem.

I was looking for a way to visualize my rather large crontab and came across your project and thought "cool, I'll try that out!". ;]

I followed the install instructions, but that actually didn't work for me - I had to use `go get` rather than `go install` (maybe a go version thing?). That downloaded the source files to `$GOPATH/src/...` and installed the package in `$GOPATH/pkg/...` (with a `cronv.a` file) - but what I cannot find at all is a `cronv` executable. I initially ran it with `go run conrv/main.go ...` from the `src` directory.

I finally ran a `go build cronv/main.go` from the `src` directory, resulting in a `main` executable file that I then copied to my `bin` directory as `cronv`, and that seems to work - but that doesn't seem like the canonical way to go about this...

I'm sure I'm just ignorant of how Go works here, but some more detail in the installation instructions to make it clearer how to generate the executable would be nice. And my apologies, I tried to do some quick googling and didn't turn up anything useful to figure out what the proper method should be here. I'm sure that somebody who knows Go wouldn't have any issues like this, so this is just to get some help for Go noobs like me.

PS: It worked great! Thanks for this neat tool! ;]

**Comment by takumakanari** [comment]
Hi @HerbCSO, 

Apologize for a late reply and very thanks for your comment.

I think the following is one of the easiest way to install `cronv` command:

```shell
# $GOPATH must be set
$ go get github.com/takumakanari/cronv/cronv
$ go build -o ./cronv github.com/takumakanari/cronv/cronv
```

then, `./cronv` will be created and you can use it.

Could you try it please?

Please let me know if you have any problem.
Thanks.

**Comment by HerbCSO** [comment]
Sorry for my delay in responding as well!

Yes, that worked out great, thank you - see, I told you it was just ignorance on my part. ;]

I did change one thing, I used `go build -o ~/bin/cronv github.com/takumakanari/cronv/cronv` instead to put the executable directly into my own `~/bin` directory, but that's really only a minor detail.

**Comment by HerbCSO** [comment]
...and I just saw you already updated the README - looks great, thank you!

**Comment by takumakanari** [comment]
@HerbCSO very thanks for your confirmation!
