### ISSUE TITLE
feature - make it possible to adjust width of labels of cron tasks

### ISSUE THREAD

**Issue by evandonovan** [takumakanari/cronv#14]
First off, thanks for this - it is amazingly useful. I even installed Go on my server to run it :)

I was just wondering if it would be possible to make it so that you could adjust the width of the column that indicates the name of the cron task - either by command line parameter, or, ideally, in the HTML page itself (though perhaps the JS plugin you are using doesn't allow that).

I ask for this because most of our cron tasks are quite lengthy in their names so it's harder to tell them apart (many begin similarly and then get truncated). As it is, you have to hover over the task in the timeline to see its full name in the tooltip, which is doable, but not ideal.

Thanks again!

**Comment by takumakanari** [comment]
Hi @evandonovan, thanks for your comment.

First, I should say very thanks to you for using my tool!

> I ask for this because most of our cron tasks are quite lengthy in their names so it's harder to tell them apart

I see, I'll think the solution to solve it, so could you wait a little more? 

Thanks.

**Comment by evandonovan** [comment]
Definitely not a rush - just would be nice to have.

**Comment by takumakanari** [comment]
Hi @evandonovan 

Sorry for my late reply.

I've released v0.2.5 with new [option](https://github.com/takumakanari/cronv#options) `-w/--width`.
It can make widely output table, but it's a little bit roughly solution.

Does this solve your issue or not?

Thanks.

**Comment by evandonovan** [comment]
Thanks - I will test it, but it may be a bit before I have the time.

**Comment by takumakanari** [comment]
no problem 👍
