### ISSUE TITLE
Support for @hourly, @daily, @weekly

### ISSUE THREAD

**Issue by robforrest-asdan** [takumakanari/cronv#27]
I've got a line in cron as follows:
`@hourly /usr/sbin/ntpdate uk.pool.ntp.org > /dev/null 2>&1 #Time Update`

While the entry shows up correctly on the graph, the title for the job gets shortened somewhat to:
`2>&1 #Time Update`

**Comment by takumakanari** [comment]
Hi @robforrest-asdan, thanks for your report.
I'll check it later.

**Comment by takumakanari** [comment]
@robforrest-asdan An issue was fixed in v0.3.2, so I'd like to request you to retry it again.
Thanks.

**Comment by robforrest-asdan** [comment]
Spot on. Well done for fixing this so quickly.
