### ISSUE TITLE
Hover text horizontal alignment issue

### ISSUE THREAD

**Issue by canada11** [takumakanari/cronv#43]
If i set the width to 1000, and generate a whole week (which I do actually do because I have a lot of entries that run at different schedules throughout the week), when scrolling to the right, the hover text isn't on the mouse but shows up off the screen on the left. To the point that it can't be read because it is so far off screen.

**Comment by takumakanari** [comment]
Hi @canada11, thanks for your report.

Please check the current version `0.4.2` that fixes both #42, #43 issues.
Let me know if there are any problems.
