### ISSUE TITLE
Microsoft Teams considers the generated html as malware

### ISSUE THREAD

**Issue by ksbn7** [takumakanari/cronv#57]
Hi,
when uploading the generated html file to Microsoft Teams it is blocked considered as malware:
![image](https://user-images.githubusercontent.com/74192406/158762129-5e551981-2690-42c0-8510-99612f4a2c6b.png)

What could be the reason for this?

Regards

**Comment by takumakanari** [comment]
Hi @ksbn7, sorry I can't estimate about the reason for this, because I don't know well about the specification of Microsoft Terms.

Could you contact Microsoft Terms support team to get more information first?

**Comment by takumakanari** [comment]
Once I close an issue. 
Feel free to reopen when there're any points in this module that I can fix (or add a new feature)  👍
